In [6]:
import numpy as np
import pandas as pd

low_memory = False

# Read csv into pandas dataframe
df = pd.read_csv('train.csv')

In [7]:
# Filter data to show yards gained on each play
yards = df.groupby('PlayId').max()[['Yards']]
yards

                Yards
PlayId
20170907000118      8
20170907000139      3
20170907000189      5
20170907000345      2
20170907000395      7
20170907000473     10
20170907000516     -1
20170907000653      0
20170907000680      9
20170907000801      9
20170907000917      2
20170907001004      3
20170907001077     13
20170907001156      4
20170907001177      0
20170907001296      4
20170907001355      4
20170907001376      4
20170907001443      0
20170907001488     16
20170907001509      9
20170907001530      4
20170907001551      2
20170907001605      2
20170907001664      3
20170907001715      1
20170907001736      4
20170907001819      4
20170907001955      7
20170907002430     10
...               ...
20181230151672      3
20181230151746      0
20181230152195      2
20181230152303      3
20181230152535      4
20181230152582      1
20181230152681      0
20181230152720      4
20181230152792     61
20181230152839     17
20181230153023      5
20181230153067      2
20181230153136      3
20181230153158      2
20181230153312      4
20181230153376      7
20181230153398      2
20181230153420      0
20181230153471      5
20181230153493     15
20181230153515      2
20181230153631     -2
20181230153844      5
20181230153866      4
20181230153888      1
20181230153910      1
20181230154035      4
20181230154082      4
20181230154135      2
20181230154157     11

[23171 rows x 1 columns]

In [8]:
# Calculate mean yards gained across plays
mean_yards_prediction = yards['Yards'].mean()
mean_yards_prediction

4.2123343834966125